name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Install dependencies
        run: sudo apt update && sudo apt install -yq xorriso qemu-system-x86

      - name: Build
        run: zig build

      - name: Make image
        run: zig build image

      - name: Run
        shell: bash
        run: |
          set +e
          timeout 30 zig build run -Dnodisplay=true
          [ $? -ne 124 ] && exit 1 || exit 0

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Lint
        run: zig fmt --check kernel/*.zig lib/*.zig build.zig
